# Generated by Django 3.1.7 on 2021-04-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspots',
            name='attractions',
            field=models.ManyToManyField(to='attractions.Attractions'),
        ),
    ]
