# Generated by Django 3.1.7 on 2021-04-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('core', '0002_touristspots_attractions'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspots',
            name='comment',
            field=models.ManyToManyField(to='comments.Comments'),
        ),
    ]
