# Generated by Django 3.1.7 on 2021-04-08 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('core', '0003_touristspots_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspots',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='address.address'),
            preserve_default=False,
        ),
    ]
