# Generated by Django 3.1.7 on 2021-04-09 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
        ('comments', '0001_initial'),
        ('address', '0001_initial'),
        ('core', '0004_touristspots_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspots',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='address.address'),
        ),
        migrations.AlterField(
            model_name='touristspots',
            name='attractions',
            field=models.ManyToManyField(null=True, to='attractions.Attractions'),
        ),
        migrations.AlterField(
            model_name='touristspots',
            name='comment',
            field=models.ManyToManyField(null=True, to='comments.Comments'),
        ),
    ]
