# Generated by Django 3.1.7 on 2021-04-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210408_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspots',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tourist_spots'),
        ),
    ]
