# Generated by Django 3.1.7 on 2021-04-13 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_touristspots_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspots',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload'),
        ),
    ]
