# Generated by Django 3.1.7 on 2021-04-08 00:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_reviews_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
